#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="payeganltd")]
public partial class pltdDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertagcPerson(agcPerson instance);
  partial void UpdateagcPerson(agcPerson instance);
  partial void DeleteagcPerson(agcPerson instance);
  partial void InsertagcPersonOrder(agcPersonOrder instance);
  partial void UpdateagcPersonOrder(agcPersonOrder instance);
  partial void DeleteagcPersonOrder(agcPersonOrder instance);
  partial void InsertagcPersonPeik(agcPersonPeik instance);
  partial void UpdateagcPersonPeik(agcPersonPeik instance);
  partial void DeleteagcPersonPeik(agcPersonPeik instance);
  partial void InsertwsOrder(wsOrder instance);
  partial void UpdatewsOrder(wsOrder instance);
  partial void DeletewsOrder(wsOrder instance);
  partial void InsertagcVarianceOrder(agcVarianceOrder instance);
  partial void UpdateagcVarianceOrder(agcVarianceOrder instance);
  partial void DeleteagcVarianceOrder(agcVarianceOrder instance);
  partial void InsertagcStatus(agcStatus instance);
  partial void UpdateagcStatus(agcStatus instance);
  partial void DeleteagcStatus(agcStatus instance);
  partial void InsertagcBalanceOrder(agcBalanceOrder instance);
  partial void UpdateagcBalanceOrder(agcBalanceOrder instance);
  partial void DeleteagcBalanceOrder(agcBalanceOrder instance);
  #endregion
	
	public pltdDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["payeganltdConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public pltdDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pltdDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pltdDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pltdDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<agcPerson> agcPersons
	{
		get
		{
			return this.GetTable<agcPerson>();
		}
	}
	
	public System.Data.Linq.Table<agcPersonOrder> agcPersonOrders
	{
		get
		{
			return this.GetTable<agcPersonOrder>();
		}
	}
	
	public System.Data.Linq.Table<agcPersonPeik> agcPersonPeiks
	{
		get
		{
			return this.GetTable<agcPersonPeik>();
		}
	}
	
	public System.Data.Linq.Table<wsOrder> wsOrders
	{
		get
		{
			return this.GetTable<wsOrder>();
		}
	}
	
	public System.Data.Linq.Table<agcVarianceOrder> agcVarianceOrders
	{
		get
		{
			return this.GetTable<agcVarianceOrder>();
		}
	}
	
	public System.Data.Linq.Table<agcStatus> agcStatus
	{
		get
		{
			return this.GetTable<agcStatus>();
		}
	}
	
	public System.Data.Linq.Table<agcBalanceOrder> agcBalanceOrders
	{
		get
		{
			return this.GetTable<agcBalanceOrder>();
		}
	}
	
	public System.Data.Linq.Table<rwdate> rwdates
	{
		get
		{
			return this.GetTable<rwdate>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dateBetweenDate", IsComposable=true)]
	public IQueryable<rwdate> dateBetweenDate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string strDateFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string strDateTo)
	{
		return this.CreateMethodCallQuery<rwdate>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strDateFrom, strDateTo);
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.agcPerson")]
public partial class agcPerson : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _strPersonMelliCode;
	
	private string _strAgcName;
	
	private string _strPersonName;
	
	private string _strPersonTel;
	
	private string _strPersonMob;
	
	private string _strHomePostCenterRef;
	
	private string _strHomeCityPreTelCode;
	
	private string _strPersonAddress;
	
	private string _strPassword;
	
	private System.Nullable<int> _numDeposit;
	
	private System.Nullable<int> _numStatus;
	
	private System.Nullable<int> _numAbnamaIncom;
	
	private System.Nullable<System.DateTime> _TimeLoginTime;
	
	private string _dateStartWorkdate;
	
	private string _strDesc;
	
	private string _strSubCatAgent;
	
	private string _strPayOrder;
	
	private System.Nullable<int> _numSendExperes;
	
	private string _strPersonMob1;
	
	private System.Nullable<int> _numExchangeRef;
	
	private System.Nullable<int> _numIsCod;
	
	private System.Nullable<int> _numIsExperes;
	
	private string _strImageName;
	
	private string _strTelegramId;
	
	private System.Nullable<int> _numOfcPersonelRef;
	
	private System.Nullable<int> _numIsMasirSelectInTeaad;
	
	private System.Nullable<double> _numPersonRate;
	
	private System.Nullable<double> _numPersonForgiveness;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstrPersonMelliCodeChanging(string value);
    partial void OnstrPersonMelliCodeChanged();
    partial void OnstrAgcNameChanging(string value);
    partial void OnstrAgcNameChanged();
    partial void OnstrPersonNameChanging(string value);
    partial void OnstrPersonNameChanged();
    partial void OnstrPersonTelChanging(string value);
    partial void OnstrPersonTelChanged();
    partial void OnstrPersonMobChanging(string value);
    partial void OnstrPersonMobChanged();
    partial void OnstrHomePostCenterRefChanging(string value);
    partial void OnstrHomePostCenterRefChanged();
    partial void OnstrHomeCityPreTelCodeChanging(string value);
    partial void OnstrHomeCityPreTelCodeChanged();
    partial void OnstrPersonAddressChanging(string value);
    partial void OnstrPersonAddressChanged();
    partial void OnstrPasswordChanging(string value);
    partial void OnstrPasswordChanged();
    partial void OnnumDepositChanging(System.Nullable<int> value);
    partial void OnnumDepositChanged();
    partial void OnnumStatusChanging(System.Nullable<int> value);
    partial void OnnumStatusChanged();
    partial void OnnumAbnamaIncomChanging(System.Nullable<int> value);
    partial void OnnumAbnamaIncomChanged();
    partial void OnTimeLoginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeLoginTimeChanged();
    partial void OndateStartWorkdateChanging(string value);
    partial void OndateStartWorkdateChanged();
    partial void OnstrDescChanging(string value);
    partial void OnstrDescChanged();
    partial void OnstrSubCatAgentChanging(string value);
    partial void OnstrSubCatAgentChanged();
    partial void OnstrPayOrderChanging(string value);
    partial void OnstrPayOrderChanged();
    partial void OnnumSendExperesChanging(System.Nullable<int> value);
    partial void OnnumSendExperesChanged();
    partial void OnstrPersonMob1Changing(string value);
    partial void OnstrPersonMob1Changed();
    partial void OnnumExchangeRefChanging(System.Nullable<int> value);
    partial void OnnumExchangeRefChanged();
    partial void OnnumIsCodChanging(System.Nullable<int> value);
    partial void OnnumIsCodChanged();
    partial void OnnumIsExperesChanging(System.Nullable<int> value);
    partial void OnnumIsExperesChanged();
    partial void OnstrImageNameChanging(string value);
    partial void OnstrImageNameChanged();
    partial void OnstrTelegramIdChanging(string value);
    partial void OnstrTelegramIdChanged();
    partial void OnnumOfcPersonelRefChanging(System.Nullable<int> value);
    partial void OnnumOfcPersonelRefChanged();
    partial void OnnumIsMasirSelectInTeaadChanging(System.Nullable<int> value);
    partial void OnnumIsMasirSelectInTeaadChanged();
    partial void OnnumPersonRateChanging(System.Nullable<double> value);
    partial void OnnumPersonRateChanged();
    partial void OnnumPersonForgivenessChanging(System.Nullable<double> value);
    partial void OnnumPersonForgivenessChanged();
    #endregion
	
	public agcPerson()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonMelliCode", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string strPersonMelliCode
	{
		get
		{
			return this._strPersonMelliCode;
		}
		set
		{
			if ((this._strPersonMelliCode != value))
			{
				this.OnstrPersonMelliCodeChanging(value);
				this.SendPropertyChanging();
				this._strPersonMelliCode = value;
				this.SendPropertyChanged("strPersonMelliCode");
				this.OnstrPersonMelliCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strAgcName", DbType="NVarChar(75)")]
	public string strAgcName
	{
		get
		{
			return this._strAgcName;
		}
		set
		{
			if ((this._strAgcName != value))
			{
				this.OnstrAgcNameChanging(value);
				this.SendPropertyChanging();
				this._strAgcName = value;
				this.SendPropertyChanged("strAgcName");
				this.OnstrAgcNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonName", DbType="NVarChar(75)")]
	public string strPersonName
	{
		get
		{
			return this._strPersonName;
		}
		set
		{
			if ((this._strPersonName != value))
			{
				this.OnstrPersonNameChanging(value);
				this.SendPropertyChanging();
				this._strPersonName = value;
				this.SendPropertyChanged("strPersonName");
				this.OnstrPersonNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonTel", DbType="NChar(50)")]
	public string strPersonTel
	{
		get
		{
			return this._strPersonTel;
		}
		set
		{
			if ((this._strPersonTel != value))
			{
				this.OnstrPersonTelChanging(value);
				this.SendPropertyChanging();
				this._strPersonTel = value;
				this.SendPropertyChanged("strPersonTel");
				this.OnstrPersonTelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonMob", DbType="NChar(15)")]
	public string strPersonMob
	{
		get
		{
			return this._strPersonMob;
		}
		set
		{
			if ((this._strPersonMob != value))
			{
				this.OnstrPersonMobChanging(value);
				this.SendPropertyChanging();
				this._strPersonMob = value;
				this.SendPropertyChanged("strPersonMob");
				this.OnstrPersonMobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strHomePostCenterRef", DbType="NChar(10)")]
	public string strHomePostCenterRef
	{
		get
		{
			return this._strHomePostCenterRef;
		}
		set
		{
			if ((this._strHomePostCenterRef != value))
			{
				this.OnstrHomePostCenterRefChanging(value);
				this.SendPropertyChanging();
				this._strHomePostCenterRef = value;
				this.SendPropertyChanged("strHomePostCenterRef");
				this.OnstrHomePostCenterRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strHomeCityPreTelCode", DbType="NChar(10)")]
	public string strHomeCityPreTelCode
	{
		get
		{
			return this._strHomeCityPreTelCode;
		}
		set
		{
			if ((this._strHomeCityPreTelCode != value))
			{
				this.OnstrHomeCityPreTelCodeChanging(value);
				this.SendPropertyChanging();
				this._strHomeCityPreTelCode = value;
				this.SendPropertyChanged("strHomeCityPreTelCode");
				this.OnstrHomeCityPreTelCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonAddress", DbType="NVarChar(250)")]
	public string strPersonAddress
	{
		get
		{
			return this._strPersonAddress;
		}
		set
		{
			if ((this._strPersonAddress != value))
			{
				this.OnstrPersonAddressChanging(value);
				this.SendPropertyChanging();
				this._strPersonAddress = value;
				this.SendPropertyChanged("strPersonAddress");
				this.OnstrPersonAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPassword", DbType="NChar(8)")]
	public string strPassword
	{
		get
		{
			return this._strPassword;
		}
		set
		{
			if ((this._strPassword != value))
			{
				this.OnstrPasswordChanging(value);
				this.SendPropertyChanging();
				this._strPassword = value;
				this.SendPropertyChanged("strPassword");
				this.OnstrPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numDeposit", DbType="Int")]
	public System.Nullable<int> numDeposit
	{
		get
		{
			return this._numDeposit;
		}
		set
		{
			if ((this._numDeposit != value))
			{
				this.OnnumDepositChanging(value);
				this.SendPropertyChanging();
				this._numDeposit = value;
				this.SendPropertyChanged("numDeposit");
				this.OnnumDepositChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numStatus", DbType="Int")]
	public System.Nullable<int> numStatus
	{
		get
		{
			return this._numStatus;
		}
		set
		{
			if ((this._numStatus != value))
			{
				this.OnnumStatusChanging(value);
				this.SendPropertyChanging();
				this._numStatus = value;
				this.SendPropertyChanged("numStatus");
				this.OnnumStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numAbnamaIncom", DbType="Int")]
	public System.Nullable<int> numAbnamaIncom
	{
		get
		{
			return this._numAbnamaIncom;
		}
		set
		{
			if ((this._numAbnamaIncom != value))
			{
				this.OnnumAbnamaIncomChanging(value);
				this.SendPropertyChanging();
				this._numAbnamaIncom = value;
				this.SendPropertyChanged("numAbnamaIncom");
				this.OnnumAbnamaIncomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeLoginTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> TimeLoginTime
	{
		get
		{
			return this._TimeLoginTime;
		}
		set
		{
			if ((this._TimeLoginTime != value))
			{
				this.OnTimeLoginTimeChanging(value);
				this.SendPropertyChanging();
				this._TimeLoginTime = value;
				this.SendPropertyChanged("TimeLoginTime");
				this.OnTimeLoginTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateStartWorkdate", DbType="NChar(10)")]
	public string dateStartWorkdate
	{
		get
		{
			return this._dateStartWorkdate;
		}
		set
		{
			if ((this._dateStartWorkdate != value))
			{
				this.OndateStartWorkdateChanging(value);
				this.SendPropertyChanging();
				this._dateStartWorkdate = value;
				this.SendPropertyChanged("dateStartWorkdate");
				this.OndateStartWorkdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strDesc", DbType="NVarChar(100)")]
	public string strDesc
	{
		get
		{
			return this._strDesc;
		}
		set
		{
			if ((this._strDesc != value))
			{
				this.OnstrDescChanging(value);
				this.SendPropertyChanging();
				this._strDesc = value;
				this.SendPropertyChanged("strDesc");
				this.OnstrDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strSubCatAgent", DbType="NVarChar(10)")]
	public string strSubCatAgent
	{
		get
		{
			return this._strSubCatAgent;
		}
		set
		{
			if ((this._strSubCatAgent != value))
			{
				this.OnstrSubCatAgentChanging(value);
				this.SendPropertyChanging();
				this._strSubCatAgent = value;
				this.SendPropertyChanged("strSubCatAgent");
				this.OnstrSubCatAgentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPayOrder", DbType="NVarChar(15)")]
	public string strPayOrder
	{
		get
		{
			return this._strPayOrder;
		}
		set
		{
			if ((this._strPayOrder != value))
			{
				this.OnstrPayOrderChanging(value);
				this.SendPropertyChanging();
				this._strPayOrder = value;
				this.SendPropertyChanged("strPayOrder");
				this.OnstrPayOrderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numSendExperes", DbType="Int")]
	public System.Nullable<int> numSendExperes
	{
		get
		{
			return this._numSendExperes;
		}
		set
		{
			if ((this._numSendExperes != value))
			{
				this.OnnumSendExperesChanging(value);
				this.SendPropertyChanging();
				this._numSendExperes = value;
				this.SendPropertyChanged("numSendExperes");
				this.OnnumSendExperesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonMob1", DbType="NChar(15)")]
	public string strPersonMob1
	{
		get
		{
			return this._strPersonMob1;
		}
		set
		{
			if ((this._strPersonMob1 != value))
			{
				this.OnstrPersonMob1Changing(value);
				this.SendPropertyChanging();
				this._strPersonMob1 = value;
				this.SendPropertyChanged("strPersonMob1");
				this.OnstrPersonMob1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numExchangeRef", DbType="Int")]
	public System.Nullable<int> numExchangeRef
	{
		get
		{
			return this._numExchangeRef;
		}
		set
		{
			if ((this._numExchangeRef != value))
			{
				this.OnnumExchangeRefChanging(value);
				this.SendPropertyChanging();
				this._numExchangeRef = value;
				this.SendPropertyChanged("numExchangeRef");
				this.OnnumExchangeRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numIsCod", DbType="Int")]
	public System.Nullable<int> numIsCod
	{
		get
		{
			return this._numIsCod;
		}
		set
		{
			if ((this._numIsCod != value))
			{
				this.OnnumIsCodChanging(value);
				this.SendPropertyChanging();
				this._numIsCod = value;
				this.SendPropertyChanged("numIsCod");
				this.OnnumIsCodChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numIsExperes", DbType="Int")]
	public System.Nullable<int> numIsExperes
	{
		get
		{
			return this._numIsExperes;
		}
		set
		{
			if ((this._numIsExperes != value))
			{
				this.OnnumIsExperesChanging(value);
				this.SendPropertyChanging();
				this._numIsExperes = value;
				this.SendPropertyChanged("numIsExperes");
				this.OnnumIsExperesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strImageName", DbType="NVarChar(200)")]
	public string strImageName
	{
		get
		{
			return this._strImageName;
		}
		set
		{
			if ((this._strImageName != value))
			{
				this.OnstrImageNameChanging(value);
				this.SendPropertyChanging();
				this._strImageName = value;
				this.SendPropertyChanged("strImageName");
				this.OnstrImageNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTelegramId", DbType="NVarChar(50)")]
	public string strTelegramId
	{
		get
		{
			return this._strTelegramId;
		}
		set
		{
			if ((this._strTelegramId != value))
			{
				this.OnstrTelegramIdChanging(value);
				this.SendPropertyChanging();
				this._strTelegramId = value;
				this.SendPropertyChanged("strTelegramId");
				this.OnstrTelegramIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOfcPersonelRef", DbType="Int")]
	public System.Nullable<int> numOfcPersonelRef
	{
		get
		{
			return this._numOfcPersonelRef;
		}
		set
		{
			if ((this._numOfcPersonelRef != value))
			{
				this.OnnumOfcPersonelRefChanging(value);
				this.SendPropertyChanging();
				this._numOfcPersonelRef = value;
				this.SendPropertyChanged("numOfcPersonelRef");
				this.OnnumOfcPersonelRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numIsMasirSelectInTeaad", DbType="Int")]
	public System.Nullable<int> numIsMasirSelectInTeaad
	{
		get
		{
			return this._numIsMasirSelectInTeaad;
		}
		set
		{
			if ((this._numIsMasirSelectInTeaad != value))
			{
				this.OnnumIsMasirSelectInTeaadChanging(value);
				this.SendPropertyChanging();
				this._numIsMasirSelectInTeaad = value;
				this.SendPropertyChanged("numIsMasirSelectInTeaad");
				this.OnnumIsMasirSelectInTeaadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPersonRate", DbType="Float")]
	public System.Nullable<double> numPersonRate
	{
		get
		{
			return this._numPersonRate;
		}
		set
		{
			if ((this._numPersonRate != value))
			{
				this.OnnumPersonRateChanging(value);
				this.SendPropertyChanging();
				this._numPersonRate = value;
				this.SendPropertyChanged("numPersonRate");
				this.OnnumPersonRateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPersonForgiveness", DbType="Float")]
	public System.Nullable<double> numPersonForgiveness
	{
		get
		{
			return this._numPersonForgiveness;
		}
		set
		{
			if ((this._numPersonForgiveness != value))
			{
				this.OnnumPersonForgivenessChanging(value);
				this.SendPropertyChanging();
				this._numPersonForgiveness = value;
				this.SendPropertyChanged("numPersonForgiveness");
				this.OnnumPersonForgivenessChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.agcPersonOrder")]
public partial class agcPersonOrder : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _strOrderRef;
	
	private string _strPersonMelliRef;
	
	private string _strDeadtimeDate;
	
	private string _strSendFactorRef;
	
	private string _strPeikSendFactorRef;
	
	private string _strReturnFactorRef;
	
	private string _strDeliveryFactorRef;
	
	private System.Nullable<int> _numMasirRef;
	
	private System.Nullable<int> _numAbnamaIncom;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstrOrderRefChanging(string value);
    partial void OnstrOrderRefChanged();
    partial void OnstrPersonMelliRefChanging(string value);
    partial void OnstrPersonMelliRefChanged();
    partial void OnstrDeadtimeDateChanging(string value);
    partial void OnstrDeadtimeDateChanged();
    partial void OnstrSendFactorRefChanging(string value);
    partial void OnstrSendFactorRefChanged();
    partial void OnstrPeikSendFactorRefChanging(string value);
    partial void OnstrPeikSendFactorRefChanged();
    partial void OnstrReturnFactorRefChanging(string value);
    partial void OnstrReturnFactorRefChanged();
    partial void OnstrDeliveryFactorRefChanging(string value);
    partial void OnstrDeliveryFactorRefChanged();
    partial void OnnumMasirRefChanging(System.Nullable<int> value);
    partial void OnnumMasirRefChanged();
    partial void OnnumAbnamaIncomChanging(System.Nullable<int> value);
    partial void OnnumAbnamaIncomChanged();
    #endregion
	
	public agcPersonOrder()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOrderRef", DbType="NVarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string strOrderRef
	{
		get
		{
			return this._strOrderRef;
		}
		set
		{
			if ((this._strOrderRef != value))
			{
				this.OnstrOrderRefChanging(value);
				this.SendPropertyChanging();
				this._strOrderRef = value;
				this.SendPropertyChanged("strOrderRef");
				this.OnstrOrderRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonMelliRef", DbType="NVarChar(20)")]
	public string strPersonMelliRef
	{
		get
		{
			return this._strPersonMelliRef;
		}
		set
		{
			if ((this._strPersonMelliRef != value))
			{
				this.OnstrPersonMelliRefChanging(value);
				this.SendPropertyChanging();
				this._strPersonMelliRef = value;
				this.SendPropertyChanged("strPersonMelliRef");
				this.OnstrPersonMelliRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strDeadtimeDate", DbType="NChar(10)")]
	public string strDeadtimeDate
	{
		get
		{
			return this._strDeadtimeDate;
		}
		set
		{
			if ((this._strDeadtimeDate != value))
			{
				this.OnstrDeadtimeDateChanging(value);
				this.SendPropertyChanging();
				this._strDeadtimeDate = value;
				this.SendPropertyChanged("strDeadtimeDate");
				this.OnstrDeadtimeDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strSendFactorRef", DbType="NVarChar(20)")]
	public string strSendFactorRef
	{
		get
		{
			return this._strSendFactorRef;
		}
		set
		{
			if ((this._strSendFactorRef != value))
			{
				this.OnstrSendFactorRefChanging(value);
				this.SendPropertyChanging();
				this._strSendFactorRef = value;
				this.SendPropertyChanged("strSendFactorRef");
				this.OnstrSendFactorRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPeikSendFactorRef", DbType="NVarChar(50)")]
	public string strPeikSendFactorRef
	{
		get
		{
			return this._strPeikSendFactorRef;
		}
		set
		{
			if ((this._strPeikSendFactorRef != value))
			{
				this.OnstrPeikSendFactorRefChanging(value);
				this.SendPropertyChanging();
				this._strPeikSendFactorRef = value;
				this.SendPropertyChanged("strPeikSendFactorRef");
				this.OnstrPeikSendFactorRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strReturnFactorRef", DbType="NVarChar(25)")]
	public string strReturnFactorRef
	{
		get
		{
			return this._strReturnFactorRef;
		}
		set
		{
			if ((this._strReturnFactorRef != value))
			{
				this.OnstrReturnFactorRefChanging(value);
				this.SendPropertyChanging();
				this._strReturnFactorRef = value;
				this.SendPropertyChanged("strReturnFactorRef");
				this.OnstrReturnFactorRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strDeliveryFactorRef", DbType="NVarChar(25)")]
	public string strDeliveryFactorRef
	{
		get
		{
			return this._strDeliveryFactorRef;
		}
		set
		{
			if ((this._strDeliveryFactorRef != value))
			{
				this.OnstrDeliveryFactorRefChanging(value);
				this.SendPropertyChanging();
				this._strDeliveryFactorRef = value;
				this.SendPropertyChanged("strDeliveryFactorRef");
				this.OnstrDeliveryFactorRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMasirRef", DbType="Int")]
	public System.Nullable<int> numMasirRef
	{
		get
		{
			return this._numMasirRef;
		}
		set
		{
			if ((this._numMasirRef != value))
			{
				this.OnnumMasirRefChanging(value);
				this.SendPropertyChanging();
				this._numMasirRef = value;
				this.SendPropertyChanged("numMasirRef");
				this.OnnumMasirRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numAbnamaIncom", DbType="Int")]
	public System.Nullable<int> numAbnamaIncom
	{
		get
		{
			return this._numAbnamaIncom;
		}
		set
		{
			if ((this._numAbnamaIncom != value))
			{
				this.OnnumAbnamaIncomChanging(value);
				this.SendPropertyChanging();
				this._numAbnamaIncom = value;
				this.SendPropertyChanged("numAbnamaIncom");
				this.OnnumAbnamaIncomChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.agcPersonPeik")]
public partial class agcPersonPeik : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _strPeikMelliCode;
	
	private string _strPersonMelliRef;
	
	private string _strPeikName;
	
	private string _strPeikTel;
	
	private string _strPeikMob;
	
	private string _strPeikAddress;
	
	private System.Nullable<int> _numStatus;
	
	private System.Nullable<int> _numPeikWage;
	
	private System.Nullable<int> _numPeikIncomeExperes;
	
	private System.Nullable<int> _numCantractRef;
	
	private string _strSendPostServiceKind;
	
	private System.Nullable<int> _numOfcPersonelCode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstrPeikMelliCodeChanging(string value);
    partial void OnstrPeikMelliCodeChanged();
    partial void OnstrPersonMelliRefChanging(string value);
    partial void OnstrPersonMelliRefChanged();
    partial void OnstrPeikNameChanging(string value);
    partial void OnstrPeikNameChanged();
    partial void OnstrPeikTelChanging(string value);
    partial void OnstrPeikTelChanged();
    partial void OnstrPeikMobChanging(string value);
    partial void OnstrPeikMobChanged();
    partial void OnstrPeikAddressChanging(string value);
    partial void OnstrPeikAddressChanged();
    partial void OnnumStatusChanging(System.Nullable<int> value);
    partial void OnnumStatusChanged();
    partial void OnnumPeikWageChanging(System.Nullable<int> value);
    partial void OnnumPeikWageChanged();
    partial void OnnumPeikIncomeExperesChanging(System.Nullable<int> value);
    partial void OnnumPeikIncomeExperesChanged();
    partial void OnnumCantractRefChanging(System.Nullable<int> value);
    partial void OnnumCantractRefChanged();
    partial void OnstrSendPostServiceKindChanging(string value);
    partial void OnstrSendPostServiceKindChanged();
    partial void OnnumOfcPersonelCodeChanging(System.Nullable<int> value);
    partial void OnnumOfcPersonelCodeChanged();
    #endregion
	
	public agcPersonPeik()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPeikMelliCode", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string strPeikMelliCode
	{
		get
		{
			return this._strPeikMelliCode;
		}
		set
		{
			if ((this._strPeikMelliCode != value))
			{
				this.OnstrPeikMelliCodeChanging(value);
				this.SendPropertyChanging();
				this._strPeikMelliCode = value;
				this.SendPropertyChanged("strPeikMelliCode");
				this.OnstrPeikMelliCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonMelliRef", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string strPersonMelliRef
	{
		get
		{
			return this._strPersonMelliRef;
		}
		set
		{
			if ((this._strPersonMelliRef != value))
			{
				this.OnstrPersonMelliRefChanging(value);
				this.SendPropertyChanging();
				this._strPersonMelliRef = value;
				this.SendPropertyChanged("strPersonMelliRef");
				this.OnstrPersonMelliRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPeikName", DbType="NVarChar(75)")]
	public string strPeikName
	{
		get
		{
			return this._strPeikName;
		}
		set
		{
			if ((this._strPeikName != value))
			{
				this.OnstrPeikNameChanging(value);
				this.SendPropertyChanging();
				this._strPeikName = value;
				this.SendPropertyChanged("strPeikName");
				this.OnstrPeikNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPeikTel", DbType="NChar(50)")]
	public string strPeikTel
	{
		get
		{
			return this._strPeikTel;
		}
		set
		{
			if ((this._strPeikTel != value))
			{
				this.OnstrPeikTelChanging(value);
				this.SendPropertyChanging();
				this._strPeikTel = value;
				this.SendPropertyChanged("strPeikTel");
				this.OnstrPeikTelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPeikMob", DbType="NChar(15)")]
	public string strPeikMob
	{
		get
		{
			return this._strPeikMob;
		}
		set
		{
			if ((this._strPeikMob != value))
			{
				this.OnstrPeikMobChanging(value);
				this.SendPropertyChanging();
				this._strPeikMob = value;
				this.SendPropertyChanged("strPeikMob");
				this.OnstrPeikMobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPeikAddress", DbType="NVarChar(200)")]
	public string strPeikAddress
	{
		get
		{
			return this._strPeikAddress;
		}
		set
		{
			if ((this._strPeikAddress != value))
			{
				this.OnstrPeikAddressChanging(value);
				this.SendPropertyChanging();
				this._strPeikAddress = value;
				this.SendPropertyChanged("strPeikAddress");
				this.OnstrPeikAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numStatus", DbType="Int")]
	public System.Nullable<int> numStatus
	{
		get
		{
			return this._numStatus;
		}
		set
		{
			if ((this._numStatus != value))
			{
				this.OnnumStatusChanging(value);
				this.SendPropertyChanging();
				this._numStatus = value;
				this.SendPropertyChanged("numStatus");
				this.OnnumStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPeikWage", DbType="Int")]
	public System.Nullable<int> numPeikWage
	{
		get
		{
			return this._numPeikWage;
		}
		set
		{
			if ((this._numPeikWage != value))
			{
				this.OnnumPeikWageChanging(value);
				this.SendPropertyChanging();
				this._numPeikWage = value;
				this.SendPropertyChanged("numPeikWage");
				this.OnnumPeikWageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPeikIncomeExperes", DbType="Int")]
	public System.Nullable<int> numPeikIncomeExperes
	{
		get
		{
			return this._numPeikIncomeExperes;
		}
		set
		{
			if ((this._numPeikIncomeExperes != value))
			{
				this.OnnumPeikIncomeExperesChanging(value);
				this.SendPropertyChanging();
				this._numPeikIncomeExperes = value;
				this.SendPropertyChanged("numPeikIncomeExperes");
				this.OnnumPeikIncomeExperesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCantractRef", DbType="Int")]
	public System.Nullable<int> numCantractRef
	{
		get
		{
			return this._numCantractRef;
		}
		set
		{
			if ((this._numCantractRef != value))
			{
				this.OnnumCantractRefChanging(value);
				this.SendPropertyChanging();
				this._numCantractRef = value;
				this.SendPropertyChanged("numCantractRef");
				this.OnnumCantractRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strSendPostServiceKind", DbType="NVarChar(10)")]
	public string strSendPostServiceKind
	{
		get
		{
			return this._strSendPostServiceKind;
		}
		set
		{
			if ((this._strSendPostServiceKind != value))
			{
				this.OnstrSendPostServiceKindChanging(value);
				this.SendPropertyChanging();
				this._strSendPostServiceKind = value;
				this.SendPropertyChanged("strSendPostServiceKind");
				this.OnstrSendPostServiceKindChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOfcPersonelCode", DbType="Int")]
	public System.Nullable<int> numOfcPersonelCode
	{
		get
		{
			return this._numOfcPersonelCode;
		}
		set
		{
			if ((this._numOfcPersonelCode != value))
			{
				this.OnnumOfcPersonelCodeChanging(value);
				this.SendPropertyChanging();
				this._numOfcPersonelCode = value;
				this.SendPropertyChanged("numOfcPersonelCode");
				this.OnnumOfcPersonelCodeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wsOrder")]
public partial class wsOrder : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _strOrderCode;
	
	private System.Nullable<int> _numOrderSalesRoomRef;
	
	private System.Nullable<int> _numOrderBuyerRef;
	
	private System.Nullable<int> _numOrderBPayTypeRef;
	
	private System.Nullable<int> _numOrderBPostServiceRef;
	
	private System.Nullable<int> _numOrderBOrderStatusRef;
	
	private System.Nullable<int> _numOrderBazaryabRef;
	
	private string _dateOrderRegisterDate;
	
	private string _dateOrderReady2SendDate;
	
	private string _dateOrderSendDate;
	
	private string _dateOrderDeliveryReturnDate;
	
	private string _strOrderDescription;
	
	private System.Nullable<int> _boolIsPrinted;
	
	private System.Nullable<int> _boolIsSalesRoomPrinted;
	
	private System.Nullable<int> _numSendPrice;
	
	private System.Nullable<int> _numExtraPrice;
	
	private string _strVarizRef;
	
	private string _strPostCode;
	
	private string _strPeikVarizRef;
	
	private System.Nullable<int> _numMaliyat;
	
	private System.Nullable<int> _numBastebandiPrice;
	
	private System.Nullable<short> _numCD_Count;
	
	private System.Nullable<short> _numDVD_Count;
	
	private System.Nullable<short> _numCover_Count;
	
	private System.Nullable<short> _numPakatType;
	
	private System.Nullable<int> _numAllGoodWeight;
	
	private System.Nullable<int> _numPakatWeight;
	
	private System.Nullable<int> _numKhadamatPrice;
	
	private string _dateReformDate;
	
	private string _strOrderBuyerPostCenterRef;
	
	private string _strOrderBuyerCityPreTelRef;
	
	private string _strOrderSalesRoomPostCenterRef;
	
	private string _strOrderSalesRoomCityPreTelRef;
	
	private System.Nullable<int> _numOrderRegisterDate;
	
	private System.Nullable<System.DateTime> _ReformDateTime;
	
	private string _dateFromGhabooldate;
	
	private string _strUserRef;
	
	private string _timeOrderRegisterTime;
	
	private System.Nullable<int> _numPoorsant;
	
	private System.Nullable<int> _numOrderParentSalesRoomRef;
	
	private System.Nullable<int> _numOrderDiscountPrice;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstrOrderCodeChanging(string value);
    partial void OnstrOrderCodeChanged();
    partial void OnnumOrderSalesRoomRefChanging(System.Nullable<int> value);
    partial void OnnumOrderSalesRoomRefChanged();
    partial void OnnumOrderBuyerRefChanging(System.Nullable<int> value);
    partial void OnnumOrderBuyerRefChanged();
    partial void OnnumOrderBPayTypeRefChanging(System.Nullable<int> value);
    partial void OnnumOrderBPayTypeRefChanged();
    partial void OnnumOrderBPostServiceRefChanging(System.Nullable<int> value);
    partial void OnnumOrderBPostServiceRefChanged();
    partial void OnnumOrderBOrderStatusRefChanging(System.Nullable<int> value);
    partial void OnnumOrderBOrderStatusRefChanged();
    partial void OnnumOrderBazaryabRefChanging(System.Nullable<int> value);
    partial void OnnumOrderBazaryabRefChanged();
    partial void OndateOrderRegisterDateChanging(string value);
    partial void OndateOrderRegisterDateChanged();
    partial void OndateOrderReady2SendDateChanging(string value);
    partial void OndateOrderReady2SendDateChanged();
    partial void OndateOrderSendDateChanging(string value);
    partial void OndateOrderSendDateChanged();
    partial void OndateOrderDeliveryReturnDateChanging(string value);
    partial void OndateOrderDeliveryReturnDateChanged();
    partial void OnstrOrderDescriptionChanging(string value);
    partial void OnstrOrderDescriptionChanged();
    partial void OnboolIsPrintedChanging(System.Nullable<int> value);
    partial void OnboolIsPrintedChanged();
    partial void OnboolIsSalesRoomPrintedChanging(System.Nullable<int> value);
    partial void OnboolIsSalesRoomPrintedChanged();
    partial void OnnumSendPriceChanging(System.Nullable<int> value);
    partial void OnnumSendPriceChanged();
    partial void OnnumExtraPriceChanging(System.Nullable<int> value);
    partial void OnnumExtraPriceChanged();
    partial void OnstrVarizRefChanging(string value);
    partial void OnstrVarizRefChanged();
    partial void OnstrPostCodeChanging(string value);
    partial void OnstrPostCodeChanged();
    partial void OnstrPeikVarizRefChanging(string value);
    partial void OnstrPeikVarizRefChanged();
    partial void OnnumMaliyatChanging(System.Nullable<int> value);
    partial void OnnumMaliyatChanged();
    partial void OnnumBastebandiPriceChanging(System.Nullable<int> value);
    partial void OnnumBastebandiPriceChanged();
    partial void OnnumCD_CountChanging(System.Nullable<short> value);
    partial void OnnumCD_CountChanged();
    partial void OnnumDVD_CountChanging(System.Nullable<short> value);
    partial void OnnumDVD_CountChanged();
    partial void OnnumCover_CountChanging(System.Nullable<short> value);
    partial void OnnumCover_CountChanged();
    partial void OnnumPakatTypeChanging(System.Nullable<short> value);
    partial void OnnumPakatTypeChanged();
    partial void OnnumAllGoodWeightChanging(System.Nullable<int> value);
    partial void OnnumAllGoodWeightChanged();
    partial void OnnumPakatWeightChanging(System.Nullable<int> value);
    partial void OnnumPakatWeightChanged();
    partial void OnnumKhadamatPriceChanging(System.Nullable<int> value);
    partial void OnnumKhadamatPriceChanged();
    partial void OndateReformDateChanging(string value);
    partial void OndateReformDateChanged();
    partial void OnstrOrderBuyerPostCenterRefChanging(string value);
    partial void OnstrOrderBuyerPostCenterRefChanged();
    partial void OnstrOrderBuyerCityPreTelRefChanging(string value);
    partial void OnstrOrderBuyerCityPreTelRefChanged();
    partial void OnstrOrderSalesRoomPostCenterRefChanging(string value);
    partial void OnstrOrderSalesRoomPostCenterRefChanged();
    partial void OnstrOrderSalesRoomCityPreTelRefChanging(string value);
    partial void OnstrOrderSalesRoomCityPreTelRefChanged();
    partial void OnnumOrderRegisterDateChanging(System.Nullable<int> value);
    partial void OnnumOrderRegisterDateChanged();
    partial void OnReformDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnReformDateTimeChanged();
    partial void OndateFromGhabooldateChanging(string value);
    partial void OndateFromGhabooldateChanged();
    partial void OnstrUserRefChanging(string value);
    partial void OnstrUserRefChanged();
    partial void OntimeOrderRegisterTimeChanging(string value);
    partial void OntimeOrderRegisterTimeChanged();
    partial void OnnumPoorsantChanging(System.Nullable<int> value);
    partial void OnnumPoorsantChanged();
    partial void OnnumOrderParentSalesRoomRefChanging(System.Nullable<int> value);
    partial void OnnumOrderParentSalesRoomRefChanged();
    partial void OnnumOrderDiscountPriceChanging(System.Nullable<int> value);
    partial void OnnumOrderDiscountPriceChanged();
    #endregion
	
	public wsOrder()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOrderCode", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string strOrderCode
	{
		get
		{
			return this._strOrderCode;
		}
		set
		{
			if ((this._strOrderCode != value))
			{
				this.OnstrOrderCodeChanging(value);
				this.SendPropertyChanging();
				this._strOrderCode = value;
				this.SendPropertyChanged("strOrderCode");
				this.OnstrOrderCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderSalesRoomRef", DbType="Int")]
	public System.Nullable<int> numOrderSalesRoomRef
	{
		get
		{
			return this._numOrderSalesRoomRef;
		}
		set
		{
			if ((this._numOrderSalesRoomRef != value))
			{
				this.OnnumOrderSalesRoomRefChanging(value);
				this.SendPropertyChanging();
				this._numOrderSalesRoomRef = value;
				this.SendPropertyChanged("numOrderSalesRoomRef");
				this.OnnumOrderSalesRoomRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderBuyerRef", DbType="Int")]
	public System.Nullable<int> numOrderBuyerRef
	{
		get
		{
			return this._numOrderBuyerRef;
		}
		set
		{
			if ((this._numOrderBuyerRef != value))
			{
				this.OnnumOrderBuyerRefChanging(value);
				this.SendPropertyChanging();
				this._numOrderBuyerRef = value;
				this.SendPropertyChanged("numOrderBuyerRef");
				this.OnnumOrderBuyerRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderBPayTypeRef", DbType="Int")]
	public System.Nullable<int> numOrderBPayTypeRef
	{
		get
		{
			return this._numOrderBPayTypeRef;
		}
		set
		{
			if ((this._numOrderBPayTypeRef != value))
			{
				this.OnnumOrderBPayTypeRefChanging(value);
				this.SendPropertyChanging();
				this._numOrderBPayTypeRef = value;
				this.SendPropertyChanged("numOrderBPayTypeRef");
				this.OnnumOrderBPayTypeRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderBPostServiceRef", DbType="Int")]
	public System.Nullable<int> numOrderBPostServiceRef
	{
		get
		{
			return this._numOrderBPostServiceRef;
		}
		set
		{
			if ((this._numOrderBPostServiceRef != value))
			{
				this.OnnumOrderBPostServiceRefChanging(value);
				this.SendPropertyChanging();
				this._numOrderBPostServiceRef = value;
				this.SendPropertyChanged("numOrderBPostServiceRef");
				this.OnnumOrderBPostServiceRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderBOrderStatusRef", DbType="Int")]
	public System.Nullable<int> numOrderBOrderStatusRef
	{
		get
		{
			return this._numOrderBOrderStatusRef;
		}
		set
		{
			if ((this._numOrderBOrderStatusRef != value))
			{
				this.OnnumOrderBOrderStatusRefChanging(value);
				this.SendPropertyChanging();
				this._numOrderBOrderStatusRef = value;
				this.SendPropertyChanged("numOrderBOrderStatusRef");
				this.OnnumOrderBOrderStatusRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderBazaryabRef", DbType="Int")]
	public System.Nullable<int> numOrderBazaryabRef
	{
		get
		{
			return this._numOrderBazaryabRef;
		}
		set
		{
			if ((this._numOrderBazaryabRef != value))
			{
				this.OnnumOrderBazaryabRefChanging(value);
				this.SendPropertyChanging();
				this._numOrderBazaryabRef = value;
				this.SendPropertyChanged("numOrderBazaryabRef");
				this.OnnumOrderBazaryabRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOrderRegisterDate", DbType="NChar(10)")]
	public string dateOrderRegisterDate
	{
		get
		{
			return this._dateOrderRegisterDate;
		}
		set
		{
			if ((this._dateOrderRegisterDate != value))
			{
				this.OndateOrderRegisterDateChanging(value);
				this.SendPropertyChanging();
				this._dateOrderRegisterDate = value;
				this.SendPropertyChanged("dateOrderRegisterDate");
				this.OndateOrderRegisterDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOrderReady2SendDate", DbType="NChar(10)")]
	public string dateOrderReady2SendDate
	{
		get
		{
			return this._dateOrderReady2SendDate;
		}
		set
		{
			if ((this._dateOrderReady2SendDate != value))
			{
				this.OndateOrderReady2SendDateChanging(value);
				this.SendPropertyChanging();
				this._dateOrderReady2SendDate = value;
				this.SendPropertyChanged("dateOrderReady2SendDate");
				this.OndateOrderReady2SendDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOrderSendDate", DbType="NChar(10)")]
	public string dateOrderSendDate
	{
		get
		{
			return this._dateOrderSendDate;
		}
		set
		{
			if ((this._dateOrderSendDate != value))
			{
				this.OndateOrderSendDateChanging(value);
				this.SendPropertyChanging();
				this._dateOrderSendDate = value;
				this.SendPropertyChanged("dateOrderSendDate");
				this.OndateOrderSendDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOrderDeliveryReturnDate", DbType="NChar(10)")]
	public string dateOrderDeliveryReturnDate
	{
		get
		{
			return this._dateOrderDeliveryReturnDate;
		}
		set
		{
			if ((this._dateOrderDeliveryReturnDate != value))
			{
				this.OndateOrderDeliveryReturnDateChanging(value);
				this.SendPropertyChanging();
				this._dateOrderDeliveryReturnDate = value;
				this.SendPropertyChanged("dateOrderDeliveryReturnDate");
				this.OndateOrderDeliveryReturnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOrderDescription", DbType="NVarChar(300)")]
	public string strOrderDescription
	{
		get
		{
			return this._strOrderDescription;
		}
		set
		{
			if ((this._strOrderDescription != value))
			{
				this.OnstrOrderDescriptionChanging(value);
				this.SendPropertyChanging();
				this._strOrderDescription = value;
				this.SendPropertyChanged("strOrderDescription");
				this.OnstrOrderDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boolIsPrinted", DbType="Int")]
	public System.Nullable<int> boolIsPrinted
	{
		get
		{
			return this._boolIsPrinted;
		}
		set
		{
			if ((this._boolIsPrinted != value))
			{
				this.OnboolIsPrintedChanging(value);
				this.SendPropertyChanging();
				this._boolIsPrinted = value;
				this.SendPropertyChanged("boolIsPrinted");
				this.OnboolIsPrintedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boolIsSalesRoomPrinted", DbType="Int")]
	public System.Nullable<int> boolIsSalesRoomPrinted
	{
		get
		{
			return this._boolIsSalesRoomPrinted;
		}
		set
		{
			if ((this._boolIsSalesRoomPrinted != value))
			{
				this.OnboolIsSalesRoomPrintedChanging(value);
				this.SendPropertyChanging();
				this._boolIsSalesRoomPrinted = value;
				this.SendPropertyChanged("boolIsSalesRoomPrinted");
				this.OnboolIsSalesRoomPrintedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numSendPrice", DbType="Int")]
	public System.Nullable<int> numSendPrice
	{
		get
		{
			return this._numSendPrice;
		}
		set
		{
			if ((this._numSendPrice != value))
			{
				this.OnnumSendPriceChanging(value);
				this.SendPropertyChanging();
				this._numSendPrice = value;
				this.SendPropertyChanged("numSendPrice");
				this.OnnumSendPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numExtraPrice", DbType="Int")]
	public System.Nullable<int> numExtraPrice
	{
		get
		{
			return this._numExtraPrice;
		}
		set
		{
			if ((this._numExtraPrice != value))
			{
				this.OnnumExtraPriceChanging(value);
				this.SendPropertyChanging();
				this._numExtraPrice = value;
				this.SendPropertyChanged("numExtraPrice");
				this.OnnumExtraPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strVarizRef", DbType="NChar(25)")]
	public string strVarizRef
	{
		get
		{
			return this._strVarizRef;
		}
		set
		{
			if ((this._strVarizRef != value))
			{
				this.OnstrVarizRefChanging(value);
				this.SendPropertyChanging();
				this._strVarizRef = value;
				this.SendPropertyChanged("strVarizRef");
				this.OnstrVarizRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPostCode", DbType="NChar(25)")]
	public string strPostCode
	{
		get
		{
			return this._strPostCode;
		}
		set
		{
			if ((this._strPostCode != value))
			{
				this.OnstrPostCodeChanging(value);
				this.SendPropertyChanging();
				this._strPostCode = value;
				this.SendPropertyChanged("strPostCode");
				this.OnstrPostCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPeikVarizRef", DbType="NChar(25)")]
	public string strPeikVarizRef
	{
		get
		{
			return this._strPeikVarizRef;
		}
		set
		{
			if ((this._strPeikVarizRef != value))
			{
				this.OnstrPeikVarizRefChanging(value);
				this.SendPropertyChanging();
				this._strPeikVarizRef = value;
				this.SendPropertyChanged("strPeikVarizRef");
				this.OnstrPeikVarizRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMaliyat", DbType="Int")]
	public System.Nullable<int> numMaliyat
	{
		get
		{
			return this._numMaliyat;
		}
		set
		{
			if ((this._numMaliyat != value))
			{
				this.OnnumMaliyatChanging(value);
				this.SendPropertyChanging();
				this._numMaliyat = value;
				this.SendPropertyChanged("numMaliyat");
				this.OnnumMaliyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numBastebandiPrice", DbType="Int")]
	public System.Nullable<int> numBastebandiPrice
	{
		get
		{
			return this._numBastebandiPrice;
		}
		set
		{
			if ((this._numBastebandiPrice != value))
			{
				this.OnnumBastebandiPriceChanging(value);
				this.SendPropertyChanging();
				this._numBastebandiPrice = value;
				this.SendPropertyChanged("numBastebandiPrice");
				this.OnnumBastebandiPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCD_Count", DbType="SmallInt")]
	public System.Nullable<short> numCD_Count
	{
		get
		{
			return this._numCD_Count;
		}
		set
		{
			if ((this._numCD_Count != value))
			{
				this.OnnumCD_CountChanging(value);
				this.SendPropertyChanging();
				this._numCD_Count = value;
				this.SendPropertyChanged("numCD_Count");
				this.OnnumCD_CountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numDVD_Count", DbType="SmallInt")]
	public System.Nullable<short> numDVD_Count
	{
		get
		{
			return this._numDVD_Count;
		}
		set
		{
			if ((this._numDVD_Count != value))
			{
				this.OnnumDVD_CountChanging(value);
				this.SendPropertyChanging();
				this._numDVD_Count = value;
				this.SendPropertyChanged("numDVD_Count");
				this.OnnumDVD_CountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCover_Count", DbType="SmallInt")]
	public System.Nullable<short> numCover_Count
	{
		get
		{
			return this._numCover_Count;
		}
		set
		{
			if ((this._numCover_Count != value))
			{
				this.OnnumCover_CountChanging(value);
				this.SendPropertyChanging();
				this._numCover_Count = value;
				this.SendPropertyChanged("numCover_Count");
				this.OnnumCover_CountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPakatType", DbType="SmallInt")]
	public System.Nullable<short> numPakatType
	{
		get
		{
			return this._numPakatType;
		}
		set
		{
			if ((this._numPakatType != value))
			{
				this.OnnumPakatTypeChanging(value);
				this.SendPropertyChanging();
				this._numPakatType = value;
				this.SendPropertyChanged("numPakatType");
				this.OnnumPakatTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numAllGoodWeight", DbType="Int")]
	public System.Nullable<int> numAllGoodWeight
	{
		get
		{
			return this._numAllGoodWeight;
		}
		set
		{
			if ((this._numAllGoodWeight != value))
			{
				this.OnnumAllGoodWeightChanging(value);
				this.SendPropertyChanging();
				this._numAllGoodWeight = value;
				this.SendPropertyChanged("numAllGoodWeight");
				this.OnnumAllGoodWeightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPakatWeight", DbType="Int")]
	public System.Nullable<int> numPakatWeight
	{
		get
		{
			return this._numPakatWeight;
		}
		set
		{
			if ((this._numPakatWeight != value))
			{
				this.OnnumPakatWeightChanging(value);
				this.SendPropertyChanging();
				this._numPakatWeight = value;
				this.SendPropertyChanged("numPakatWeight");
				this.OnnumPakatWeightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numKhadamatPrice", DbType="Int")]
	public System.Nullable<int> numKhadamatPrice
	{
		get
		{
			return this._numKhadamatPrice;
		}
		set
		{
			if ((this._numKhadamatPrice != value))
			{
				this.OnnumKhadamatPriceChanging(value);
				this.SendPropertyChanging();
				this._numKhadamatPrice = value;
				this.SendPropertyChanged("numKhadamatPrice");
				this.OnnumKhadamatPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateReformDate", DbType="NChar(10)")]
	public string dateReformDate
	{
		get
		{
			return this._dateReformDate;
		}
		set
		{
			if ((this._dateReformDate != value))
			{
				this.OndateReformDateChanging(value);
				this.SendPropertyChanging();
				this._dateReformDate = value;
				this.SendPropertyChanged("dateReformDate");
				this.OndateReformDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOrderBuyerPostCenterRef", DbType="NChar(10)")]
	public string strOrderBuyerPostCenterRef
	{
		get
		{
			return this._strOrderBuyerPostCenterRef;
		}
		set
		{
			if ((this._strOrderBuyerPostCenterRef != value))
			{
				this.OnstrOrderBuyerPostCenterRefChanging(value);
				this.SendPropertyChanging();
				this._strOrderBuyerPostCenterRef = value;
				this.SendPropertyChanged("strOrderBuyerPostCenterRef");
				this.OnstrOrderBuyerPostCenterRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOrderBuyerCityPreTelRef", DbType="NChar(10)")]
	public string strOrderBuyerCityPreTelRef
	{
		get
		{
			return this._strOrderBuyerCityPreTelRef;
		}
		set
		{
			if ((this._strOrderBuyerCityPreTelRef != value))
			{
				this.OnstrOrderBuyerCityPreTelRefChanging(value);
				this.SendPropertyChanging();
				this._strOrderBuyerCityPreTelRef = value;
				this.SendPropertyChanged("strOrderBuyerCityPreTelRef");
				this.OnstrOrderBuyerCityPreTelRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOrderSalesRoomPostCenterRef", DbType="NChar(10)")]
	public string strOrderSalesRoomPostCenterRef
	{
		get
		{
			return this._strOrderSalesRoomPostCenterRef;
		}
		set
		{
			if ((this._strOrderSalesRoomPostCenterRef != value))
			{
				this.OnstrOrderSalesRoomPostCenterRefChanging(value);
				this.SendPropertyChanging();
				this._strOrderSalesRoomPostCenterRef = value;
				this.SendPropertyChanged("strOrderSalesRoomPostCenterRef");
				this.OnstrOrderSalesRoomPostCenterRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOrderSalesRoomCityPreTelRef", DbType="NChar(10)")]
	public string strOrderSalesRoomCityPreTelRef
	{
		get
		{
			return this._strOrderSalesRoomCityPreTelRef;
		}
		set
		{
			if ((this._strOrderSalesRoomCityPreTelRef != value))
			{
				this.OnstrOrderSalesRoomCityPreTelRefChanging(value);
				this.SendPropertyChanging();
				this._strOrderSalesRoomCityPreTelRef = value;
				this.SendPropertyChanged("strOrderSalesRoomCityPreTelRef");
				this.OnstrOrderSalesRoomCityPreTelRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderRegisterDate", DbType="Int")]
	public System.Nullable<int> numOrderRegisterDate
	{
		get
		{
			return this._numOrderRegisterDate;
		}
		set
		{
			if ((this._numOrderRegisterDate != value))
			{
				this.OnnumOrderRegisterDateChanging(value);
				this.SendPropertyChanging();
				this._numOrderRegisterDate = value;
				this.SendPropertyChanged("numOrderRegisterDate");
				this.OnnumOrderRegisterDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReformDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> ReformDateTime
	{
		get
		{
			return this._ReformDateTime;
		}
		set
		{
			if ((this._ReformDateTime != value))
			{
				this.OnReformDateTimeChanging(value);
				this.SendPropertyChanging();
				this._ReformDateTime = value;
				this.SendPropertyChanged("ReformDateTime");
				this.OnReformDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateFromGhabooldate", DbType="NChar(21)")]
	public string dateFromGhabooldate
	{
		get
		{
			return this._dateFromGhabooldate;
		}
		set
		{
			if ((this._dateFromGhabooldate != value))
			{
				this.OndateFromGhabooldateChanging(value);
				this.SendPropertyChanging();
				this._dateFromGhabooldate = value;
				this.SendPropertyChanged("dateFromGhabooldate");
				this.OndateFromGhabooldateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strUserRef", DbType="NChar(25)")]
	public string strUserRef
	{
		get
		{
			return this._strUserRef;
		}
		set
		{
			if ((this._strUserRef != value))
			{
				this.OnstrUserRefChanging(value);
				this.SendPropertyChanging();
				this._strUserRef = value;
				this.SendPropertyChanged("strUserRef");
				this.OnstrUserRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeOrderRegisterTime", DbType="NChar(5)")]
	public string timeOrderRegisterTime
	{
		get
		{
			return this._timeOrderRegisterTime;
		}
		set
		{
			if ((this._timeOrderRegisterTime != value))
			{
				this.OntimeOrderRegisterTimeChanging(value);
				this.SendPropertyChanging();
				this._timeOrderRegisterTime = value;
				this.SendPropertyChanged("timeOrderRegisterTime");
				this.OntimeOrderRegisterTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPoorsant", DbType="Int")]
	public System.Nullable<int> numPoorsant
	{
		get
		{
			return this._numPoorsant;
		}
		set
		{
			if ((this._numPoorsant != value))
			{
				this.OnnumPoorsantChanging(value);
				this.SendPropertyChanging();
				this._numPoorsant = value;
				this.SendPropertyChanged("numPoorsant");
				this.OnnumPoorsantChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderParentSalesRoomRef", DbType="Int")]
	public System.Nullable<int> numOrderParentSalesRoomRef
	{
		get
		{
			return this._numOrderParentSalesRoomRef;
		}
		set
		{
			if ((this._numOrderParentSalesRoomRef != value))
			{
				this.OnnumOrderParentSalesRoomRefChanging(value);
				this.SendPropertyChanging();
				this._numOrderParentSalesRoomRef = value;
				this.SendPropertyChanged("numOrderParentSalesRoomRef");
				this.OnnumOrderParentSalesRoomRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrderDiscountPrice", DbType="Int")]
	public System.Nullable<int> numOrderDiscountPrice
	{
		get
		{
			return this._numOrderDiscountPrice;
		}
		set
		{
			if ((this._numOrderDiscountPrice != value))
			{
				this.OnnumOrderDiscountPriceChanging(value);
				this.SendPropertyChanging();
				this._numOrderDiscountPrice = value;
				this.SendPropertyChanged("numOrderDiscountPrice");
				this.OnnumOrderDiscountPriceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.agcVarianceOrder")]
public partial class agcVarianceOrder : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _numVarianceOrderCode;
	
	private string _strOrderRef;
	
	private System.Nullable<int> _numStatus;
	
	private string _dateRegisterDate;
	
	private string _strPersonMelliRef;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumVarianceOrderCodeChanging(int value);
    partial void OnnumVarianceOrderCodeChanged();
    partial void OnstrOrderRefChanging(string value);
    partial void OnstrOrderRefChanged();
    partial void OnnumStatusChanging(System.Nullable<int> value);
    partial void OnnumStatusChanged();
    partial void OndateRegisterDateChanging(string value);
    partial void OndateRegisterDateChanged();
    partial void OnstrPersonMelliRefChanging(string value);
    partial void OnstrPersonMelliRefChanged();
    #endregion
	
	public agcVarianceOrder()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVarianceOrderCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int numVarianceOrderCode
	{
		get
		{
			return this._numVarianceOrderCode;
		}
		set
		{
			if ((this._numVarianceOrderCode != value))
			{
				this.OnnumVarianceOrderCodeChanging(value);
				this.SendPropertyChanging();
				this._numVarianceOrderCode = value;
				this.SendPropertyChanged("numVarianceOrderCode");
				this.OnnumVarianceOrderCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOrderRef", DbType="NChar(20)")]
	public string strOrderRef
	{
		get
		{
			return this._strOrderRef;
		}
		set
		{
			if ((this._strOrderRef != value))
			{
				this.OnstrOrderRefChanging(value);
				this.SendPropertyChanging();
				this._strOrderRef = value;
				this.SendPropertyChanged("strOrderRef");
				this.OnstrOrderRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numStatus", DbType="Int")]
	public System.Nullable<int> numStatus
	{
		get
		{
			return this._numStatus;
		}
		set
		{
			if ((this._numStatus != value))
			{
				this.OnnumStatusChanging(value);
				this.SendPropertyChanging();
				this._numStatus = value;
				this.SendPropertyChanged("numStatus");
				this.OnnumStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateRegisterDate", DbType="NChar(10)")]
	public string dateRegisterDate
	{
		get
		{
			return this._dateRegisterDate;
		}
		set
		{
			if ((this._dateRegisterDate != value))
			{
				this.OndateRegisterDateChanging(value);
				this.SendPropertyChanging();
				this._dateRegisterDate = value;
				this.SendPropertyChanged("dateRegisterDate");
				this.OndateRegisterDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonMelliRef", DbType="NChar(10)")]
	public string strPersonMelliRef
	{
		get
		{
			return this._strPersonMelliRef;
		}
		set
		{
			if ((this._strPersonMelliRef != value))
			{
				this.OnstrPersonMelliRefChanging(value);
				this.SendPropertyChanging();
				this._strPersonMelliRef = value;
				this.SendPropertyChanged("strPersonMelliRef");
				this.OnstrPersonMelliRefChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.agcStatus")]
public partial class agcStatus : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _numAgancyStatusCode;
	
	private string _strAgancyStatusTitle;
	
	private string _strAgancyStatusDesc;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumAgancyStatusCodeChanging(int value);
    partial void OnnumAgancyStatusCodeChanged();
    partial void OnstrAgancyStatusTitleChanging(string value);
    partial void OnstrAgancyStatusTitleChanged();
    partial void OnstrAgancyStatusDescChanging(string value);
    partial void OnstrAgancyStatusDescChanged();
    #endregion
	
	public agcStatus()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numAgancyStatusCode", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int numAgancyStatusCode
	{
		get
		{
			return this._numAgancyStatusCode;
		}
		set
		{
			if ((this._numAgancyStatusCode != value))
			{
				this.OnnumAgancyStatusCodeChanging(value);
				this.SendPropertyChanging();
				this._numAgancyStatusCode = value;
				this.SendPropertyChanged("numAgancyStatusCode");
				this.OnnumAgancyStatusCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strAgancyStatusTitle", DbType="NVarChar(100)")]
	public string strAgancyStatusTitle
	{
		get
		{
			return this._strAgancyStatusTitle;
		}
		set
		{
			if ((this._strAgancyStatusTitle != value))
			{
				this.OnstrAgancyStatusTitleChanging(value);
				this.SendPropertyChanging();
				this._strAgancyStatusTitle = value;
				this.SendPropertyChanged("strAgancyStatusTitle");
				this.OnstrAgancyStatusTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strAgancyStatusDesc", DbType="NVarChar(200)")]
	public string strAgancyStatusDesc
	{
		get
		{
			return this._strAgancyStatusDesc;
		}
		set
		{
			if ((this._strAgancyStatusDesc != value))
			{
				this.OnstrAgancyStatusDescChanging(value);
				this.SendPropertyChanging();
				this._strAgancyStatusDesc = value;
				this.SendPropertyChanged("strAgancyStatusDesc");
				this.OnstrAgancyStatusDescChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.agcBalanceOrder")]
public partial class agcBalanceOrder : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _numBalanceOrder;
	
	private string _strReturnOrderCode;
	
	private string _strNewOrderCode;
	
	private string _dateRegisterDate;
	
	private System.Nullable<int> _numStatus;
	
	private string _strPersonMelliRef;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumBalanceOrderChanging(int value);
    partial void OnnumBalanceOrderChanged();
    partial void OnstrReturnOrderCodeChanging(string value);
    partial void OnstrReturnOrderCodeChanged();
    partial void OnstrNewOrderCodeChanging(string value);
    partial void OnstrNewOrderCodeChanged();
    partial void OndateRegisterDateChanging(string value);
    partial void OndateRegisterDateChanged();
    partial void OnnumStatusChanging(System.Nullable<int> value);
    partial void OnnumStatusChanged();
    partial void OnstrPersonMelliRefChanging(string value);
    partial void OnstrPersonMelliRefChanged();
    #endregion
	
	public agcBalanceOrder()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numBalanceOrder", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int numBalanceOrder
	{
		get
		{
			return this._numBalanceOrder;
		}
		set
		{
			if ((this._numBalanceOrder != value))
			{
				this.OnnumBalanceOrderChanging(value);
				this.SendPropertyChanging();
				this._numBalanceOrder = value;
				this.SendPropertyChanged("numBalanceOrder");
				this.OnnumBalanceOrderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strReturnOrderCode", DbType="NChar(25)")]
	public string strReturnOrderCode
	{
		get
		{
			return this._strReturnOrderCode;
		}
		set
		{
			if ((this._strReturnOrderCode != value))
			{
				this.OnstrReturnOrderCodeChanging(value);
				this.SendPropertyChanging();
				this._strReturnOrderCode = value;
				this.SendPropertyChanged("strReturnOrderCode");
				this.OnstrReturnOrderCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNewOrderCode", DbType="NChar(25)")]
	public string strNewOrderCode
	{
		get
		{
			return this._strNewOrderCode;
		}
		set
		{
			if ((this._strNewOrderCode != value))
			{
				this.OnstrNewOrderCodeChanging(value);
				this.SendPropertyChanging();
				this._strNewOrderCode = value;
				this.SendPropertyChanged("strNewOrderCode");
				this.OnstrNewOrderCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateRegisterDate", DbType="NChar(10)")]
	public string dateRegisterDate
	{
		get
		{
			return this._dateRegisterDate;
		}
		set
		{
			if ((this._dateRegisterDate != value))
			{
				this.OndateRegisterDateChanging(value);
				this.SendPropertyChanging();
				this._dateRegisterDate = value;
				this.SendPropertyChanged("dateRegisterDate");
				this.OndateRegisterDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numStatus", DbType="Int")]
	public System.Nullable<int> numStatus
	{
		get
		{
			return this._numStatus;
		}
		set
		{
			if ((this._numStatus != value))
			{
				this.OnnumStatusChanging(value);
				this.SendPropertyChanging();
				this._numStatus = value;
				this.SendPropertyChanged("numStatus");
				this.OnnumStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPersonMelliRef", DbType="NChar(10)")]
	public string strPersonMelliRef
	{
		get
		{
			return this._strPersonMelliRef;
		}
		set
		{
			if ((this._strPersonMelliRef != value))
			{
				this.OnstrPersonMelliRefChanging(value);
				this.SendPropertyChanging();
				this._strPersonMelliRef = value;
				this.SendPropertyChanged("strPersonMelliRef");
				this.OnstrPersonMelliRefChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
public partial class rwdate
{
	
	private string _strdate;
	
	public rwdate()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strdate", DbType="nchar(10)", CanBeNull=false)]
	public string strdate
	{
		get
		{
			return this._strdate;
		}
		set
		{
			if ((this._strdate != value))
			{
				this._strdate = value;
			}
		}
	}
}
#pragma warning restore 1591
