#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="User")]
public partial class UsersDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertusrMessage(usrMessage instance);
  partial void UpdateusrMessage(usrMessage instance);
  partial void DeleteusrMessage(usrMessage instance);
  #endregion
	
	public UsersDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["UserConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public UsersDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public UsersDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public UsersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public UsersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<usrMessage> usrMessages
	{
		get
		{
			return this.GetTable<usrMessage>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usrInsertMessage")]
	public int usrInsertMessage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numUserRefFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GRnumUserRefTo", DbType="NVarChar(1000)")] string gRnumUserRefTo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string strMsgSubject, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string strMsgBody, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numMsgStatus)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numUserRefFrom, gRnumUserRefTo, strMsgSubject, strMsgBody, numMsgStatus);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usrMessage")]
public partial class usrMessage : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _numMsgCode;
	
	private System.Nullable<int> _numUserRefFrom;
	
	private System.Nullable<int> _numUserRefTo;
	
	private string _strMsgSubject;
	
	private string _strMsgBody;
	
	private System.Nullable<int> _numMsgStatus;
	
	private string _dateMsgRegisterDate;
	
	private string _dateMsgRegisterTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumMsgCodeChanging(int value);
    partial void OnnumMsgCodeChanged();
    partial void OnnumUserRefFromChanging(System.Nullable<int> value);
    partial void OnnumUserRefFromChanged();
    partial void OnnumUserRefToChanging(System.Nullable<int> value);
    partial void OnnumUserRefToChanged();
    partial void OnstrMsgSubjectChanging(string value);
    partial void OnstrMsgSubjectChanged();
    partial void OnstrMsgBodyChanging(string value);
    partial void OnstrMsgBodyChanged();
    partial void OnnumMsgStatusChanging(System.Nullable<int> value);
    partial void OnnumMsgStatusChanged();
    partial void OndateMsgRegisterDateChanging(string value);
    partial void OndateMsgRegisterDateChanged();
    partial void OndateMsgRegisterTimeChanging(string value);
    partial void OndateMsgRegisterTimeChanged();
    #endregion
	
	public usrMessage()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMsgCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int numMsgCode
	{
		get
		{
			return this._numMsgCode;
		}
		set
		{
			if ((this._numMsgCode != value))
			{
				this.OnnumMsgCodeChanging(value);
				this.SendPropertyChanging();
				this._numMsgCode = value;
				this.SendPropertyChanged("numMsgCode");
				this.OnnumMsgCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numUserRefFrom", DbType="Int")]
	public System.Nullable<int> numUserRefFrom
	{
		get
		{
			return this._numUserRefFrom;
		}
		set
		{
			if ((this._numUserRefFrom != value))
			{
				this.OnnumUserRefFromChanging(value);
				this.SendPropertyChanging();
				this._numUserRefFrom = value;
				this.SendPropertyChanged("numUserRefFrom");
				this.OnnumUserRefFromChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numUserRefTo", DbType="Int")]
	public System.Nullable<int> numUserRefTo
	{
		get
		{
			return this._numUserRefTo;
		}
		set
		{
			if ((this._numUserRefTo != value))
			{
				this.OnnumUserRefToChanging(value);
				this.SendPropertyChanging();
				this._numUserRefTo = value;
				this.SendPropertyChanged("numUserRefTo");
				this.OnnumUserRefToChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strMsgSubject", DbType="NVarChar(200)")]
	public string strMsgSubject
	{
		get
		{
			return this._strMsgSubject;
		}
		set
		{
			if ((this._strMsgSubject != value))
			{
				this.OnstrMsgSubjectChanging(value);
				this.SendPropertyChanging();
				this._strMsgSubject = value;
				this.SendPropertyChanged("strMsgSubject");
				this.OnstrMsgSubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strMsgBody", DbType="NVarChar(2000)")]
	public string strMsgBody
	{
		get
		{
			return this._strMsgBody;
		}
		set
		{
			if ((this._strMsgBody != value))
			{
				this.OnstrMsgBodyChanging(value);
				this.SendPropertyChanging();
				this._strMsgBody = value;
				this.SendPropertyChanged("strMsgBody");
				this.OnstrMsgBodyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMsgStatus", DbType="Int")]
	public System.Nullable<int> numMsgStatus
	{
		get
		{
			return this._numMsgStatus;
		}
		set
		{
			if ((this._numMsgStatus != value))
			{
				this.OnnumMsgStatusChanging(value);
				this.SendPropertyChanging();
				this._numMsgStatus = value;
				this.SendPropertyChanged("numMsgStatus");
				this.OnnumMsgStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateMsgRegisterDate", DbType="NChar(10)")]
	public string dateMsgRegisterDate
	{
		get
		{
			return this._dateMsgRegisterDate;
		}
		set
		{
			if ((this._dateMsgRegisterDate != value))
			{
				this.OndateMsgRegisterDateChanging(value);
				this.SendPropertyChanging();
				this._dateMsgRegisterDate = value;
				this.SendPropertyChanged("dateMsgRegisterDate");
				this.OndateMsgRegisterDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateMsgRegisterTime", DbType="NChar(5)")]
	public string dateMsgRegisterTime
	{
		get
		{
			return this._dateMsgRegisterTime;
		}
		set
		{
			if ((this._dateMsgRegisterTime != value))
			{
				this.OndateMsgRegisterTimeChanging(value);
				this.SendPropertyChanging();
				this._dateMsgRegisterTime = value;
				this.SendPropertyChanged("dateMsgRegisterTime");
				this.OndateMsgRegisterTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
